services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PRODUCTION=false
      - SECRET_KEY=YOUR_KEY
      - EMAIL_HOST_USER=YOUR_EMAIL
      - EMAIL_HOST_PASSWORD=YOUR_PASSWORD
      
