services:
  app:
    image: atomics42/certification_system-app:latest
    ports:
      - "8000:8000"
    volumes:
      - /var/database/locus_certification_system:/app/db
      - /var/www/static:/app/static

  nginx:
    image: atomics42/certification_system-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - /var/www/static:/static