# Generated by Django 4.1.1 on 2022-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
