# Generated by Django 4.1.1 on 2022-10-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0002_alter_certificate_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="active",
            new_name="email_sent",
        ),
    ]
