# Generated by Django 4.1.1 on 2022-10-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0003_rename_active_certificate_email_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
